version: "3.4"

services:
  oneauthservice:
    image: oneauthservice
    container_name: oneauthservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010
      APP_URL: https://oneauth-app.ioak.io
      PORT: 8005
    ports:
      - 8005:8005
    networks:
      ioak-net:
        aliases:
          - oneauthservice.docker

networks:
  ioak-net:
    external: true
