version: "3.4"

services:
  oneauthserver:
    image: oneauthserver
    container_name: oneauthserver
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010
      APP_URL: https://oneauth-app.ioak.io
      PORT: 8025
    ports:
      - 8025:8025
    networks:
      ioak-net:
        aliases:
          - oneauthserver.docker

networks:
  ioak-net:
    name: ioak-network
