from django.urls import path
from django.conf.urls import url

from . import oa_views, space_views, appspace_views

urlpatterns = [
    path('space/<str:space_id>/signup', space_views.signup),
    path('space/<str:space_id>/resetpasswordlink', space_views.reset_password_link),
    path('space/<str:space_id>/verifypasswordlink/<str:auth_code>', space_views.verify_password_link),
    path('space/<str:space_id>/emailconfirmationlink', space_views.email_confirmation_link),
    path('space/<str:space_id>/verifyemailconfirmationlink/<str:auth_code>', space_views.verify_email_confirmation_link),
    path('space/<str:space_id>/resetpassword/<str:auth_code>', space_views.reset_password),
    path('space/<str:space_id>/changepassword', space_views.change_password),
    path('space/<str:space_id>/updateprofile', space_views.update_profile),
    path('space/<str:space_id>/authorize', space_views.authorize),
    path('space/<str:space_id>/authorize/google/<str:token>', space_views.authorize_google),
    path('space/<str:space_id>/authorize/facebook', space_views.authorize_facebook),
    path('space/<str:space_id>/session/<str:auth_key>', space_views.get_session_token),
    path('space/<str:space_id>/session/<str:auth_key>/invalidate', space_views.invalidate_session_token),
    path('oa/signup', oa_views.signup),
    path('oa/resetpasswordlink', oa_views.reset_password_link),
    path('oa/verifypasswordlink/<str:auth_code>', oa_views.verify_password_link),
    path('oa/emailconfirmationlink', oa_views.email_confirmation_link),
    path('oa/verifyemailconfirmationlink/<str:auth_code>', oa_views.verify_email_confirmation_link),
    path('oa/resetpassword/<str:auth_code>', oa_views.reset_password),
    path('oa/changepassword', oa_views.change_password),
    path('oa/updateprofile', oa_views.update_profile),
    path('oa/authorize', oa_views.authorize),
    path('oa/authorize/google/<str:token>', oa_views.authorize_google),
    path('oa/authorize/facebook', oa_views.authorize_facebook),
    path('oa/session/<str:auth_key>', oa_views.get_session_token),
    path('oa/session/<str:auth_key>/invalidate', oa_views.invalidate_session_token),
    path('', space_views.get_all_users),
    path('appspace/<str:appspace_id>/signup', appspace_views.signup),
    path('appspace/<str:appspace_id>/resetpasswordlink', appspace_views.reset_password_link),
    path('appspace/<str:appspace_id>/verifypasswordlink/<str:auth_code>', appspace_views.verify_password_link),
    path('appspace/<str:appspace_id>/emailconfirmationlink', appspace_views.email_confirmation_link),
    path('appspace/<str:appspace_id>/verifyemailconfirmationlink/<str:auth_code>', appspace_views.verify_email_confirmation_link),
    path('appspace/<str:appspace_id>/resetpassword/<str:auth_code>', appspace_views.reset_password),
    path('appspace/<str:appspace_id>/changepassword', appspace_views.change_password),
    path('appspace/<str:appspace_id>/updateprofile', appspace_views.update_profile),
    path('appspace/<str:appspace_id>/authorize', appspace_views.authorize),
    path('appspace/<str:appspace_id>/authorize/google/<str:token>', appspace_views.authorize_google),
    path('appspace/<str:appspace_id>/authorize/facebook', appspace_views.authorize_facebook),
    path('appspace/<str:appspace_id>/session/<str:auth_key>', appspace_views.get_session_token),
    path('appspace/<str:appspace_id>/session/<str:auth_key>/invalidate', appspace_views.invalidate_session_token),
]
